import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fr';

interface Translations {
  [key: string]: {
    en: string;
    fr: string;
  };
}

export const translations: Translations = {
  welcome: { en: 'Welcome to VibeShop', fr: 'Bienvenue sur VibeShop' },
  builder_title: { en: 'AI Store Builder', fr: 'Constructeur de Boutique IA' },
  builder_desc: { en: 'Describe your dream store and let AI build it for you.', fr: 'Décrivez la boutique de vos rêves et laissez l\'IA la construire pour vous.' },
  dashboard: { en: 'Dashboard', fr: 'Tableau de bord' },
  settings: { en: 'Settings', fr: 'Paramètres' },
  reports: { en: 'Reports', fr: 'Rapports' },
  create_store: { en: 'Create Store', fr: 'Créer une boutique' },
  chat_placeholder: { en: 'Type your store idea here...', fr: 'Tapez votre idée de boutique ici...' },
  generating: { en: 'Generating your store...', fr: 'Génération de votre boutique...' },
  total_sales: { en: 'Total Sales', fr: 'Ventes Totales' },
  total_orders: { en: 'Total Orders', fr: 'Commandes Totales' },
  conversion_rate: { en: 'Conversion Rate', fr: 'Taux de Conversion' },
  revenue: { en: 'Revenue', fr: 'Revenu' },
  traffic: { en: 'Traffic', fr: 'Trafic' },
  best_sellers: { en: 'Best Sellers', fr: 'Meilleures Ventes' },
  marketing_tips: { en: 'Marketing Tips', fr: 'Conseils Marketing' },
  add_to_cart: { en: 'Add to Cart', fr: 'Ajouter au Panier' },
  checkout: { en: 'Checkout', fr: 'Paiement' },
  cart: { en: 'Cart', fr: 'Panier' },
  about: { en: 'About Us', fr: 'À Propos' },
  contact: { en: 'Contact', fr: 'Contact' },
  pricing: { en: 'Pricing', fr: 'Tarification' },
  features: { en: 'Features', fr: 'Fonctionnalités' },
  process: { en: 'Process', fr: 'Processus' },
  sign_in: { en: 'Sign In', fr: 'Se Connecter' },
  get_started: { en: 'Get Started', fr: 'Commencer' },
  build_now: { en: 'Build Your Store Now', fr: 'Créez votre boutique maintenant' },
  ready_to_start: { en: 'Ready to start your empire?', fr: 'Prêt à lancer votre empire ?' },
  join_community: { en: 'Join 2,000+ store owners who built their business with VibeShop.', fr: 'Rejoignez plus de 2 000 propriétaires de boutiques qui ont bâti leur entreprise avec VibeShop.' },
  product_finder: { en: 'AI Product Finder', fr: 'Recherche de Produits IA' },
  supplier_finder: { en: 'AI Supplier Finder', fr: 'Recherche de Fournisseurs IA' },
  video_marketing: { en: 'AI Video Marketing', fr: 'Marketing Vidéo IA' },
  collaboration: { en: 'Collaboration', fr: 'Collaboration' },
  orders: { en: 'Orders', fr: 'Commandes' },
  customers: { en: 'Customers', fr: 'Clients' },
  payments: { en: 'Payments', fr: 'Paiements' },
  supplier_orders: { en: 'Supplier Orders', fr: 'Commandes Fournisseurs' },
  billing: { en: 'Billing', fr: 'Facturation' },
  subscription: { en: 'Subscription', fr: 'Abonnement' },
  active: { en: 'Active', fr: 'Actif' },
  canceled: { en: 'Canceled', fr: 'Annulé' },
  none: { en: 'None', fr: 'Aucun' },
  cancel_sub: { en: 'Cancel Subscription', fr: 'Annuler l\'abonnement' },
  current_plan: { en: 'Current Plan', fr: 'Plan Actuel' },
  date: { en: 'Date', fr: 'Date' },
  amount: { en: 'Amount', fr: 'Montant' },
  status: { en: 'Status', fr: 'Statut' },
  customer: { en: 'Customer', fr: 'Client' },
  id: { en: 'ID', fr: 'ID' },
  builder_welcome: { en: 'Describe your dream store and let AI build it for you.', fr: 'Décrivez la boutique de vos rêves et laissez l\'IA la construire pour vous.' },
  builder_placeholder: { en: 'e.g., A luxury watch store with a minimalist dark theme...', fr: 'ex: Une boutique de montres de luxe avec un thème sombre minimaliste...' },
  builder_update: { en: 'Update Store', fr: 'Mettre à jour la boutique' },
  builder_generate: { en: 'Generate Store', fr: 'Générer la boutique' },
  payment_method: { en: 'Payment Method', fr: 'Méthode de Paiement' },
  change_plan: { en: 'Change or Upgrade Plan', fr: 'Changer ou Améliorer le Plan' },
  profile_info: { en: 'Profile Information', fr: 'Informations du Profil' },
  preferences: { en: 'Preferences', fr: 'Préférences' },
  security: { en: 'Security', fr: 'Sécurité' },
  danger_zone: { en: 'Danger Zone', fr: 'Zone de Danger' },
  delete_account: { en: 'Delete Account', fr: 'Supprimer le Compte' },
  language_label: { en: 'Language', fr: 'Langue' },
  timezone_label: { en: 'Timezone', fr: 'Fuseau Horaire' },
  password_label: { en: 'Password', fr: 'Mot de Passe' },
  two_factor: { en: 'Two-Factor Auth', fr: 'Authentification à Deux Facteurs' },
  edit: { en: 'Edit', fr: 'Modifier' },
  save: { en: 'Save', fr: 'Enregistrer' },
  cancel: { en: 'Cancel', fr: 'Annuler' },
  live_preview: { en: 'Live Preview', fr: 'Aperçu en Direct' },
  most_popular: { en: 'Most Popular', fr: 'Le Plus Populaire' },
  per_month: { en: 'per month', fr: 'par mois' },
  commission_on_sales: { en: 'Commission on sales', fr: 'Commission sur les ventes' },
  unlimited: { en: 'Unlimited', fr: 'Illimité' },
  priority_support: { en: 'Priority Support', fr: 'Support Prioritaire' },
  advanced_analytics: { en: 'Advanced Analytics', fr: 'Analyses Avancées' },
  custom_domain: { en: 'Custom Domain', fr: 'Domaine Personnalisé' },
  ai_suggestions: { en: 'AI Suggestions', fr: 'Suggestions IA' },
  marketing_recs: { en: 'Marketing Recommendations', fr: 'Recommandations Marketing' },
  supplier_intelligence: { en: 'AI Supplier Intelligence', fr: 'Intelligence Fournisseur IA' },
  automation_tools: { en: 'Automation Tools', fr: 'Outils d\'Automatisation' },
  business_insights: { en: 'Business Insights', fr: 'Aperçus Commerciaux' },
  generate_videos: { en: 'Generate Videos', fr: 'Générer des Vidéos' },
  invite_collaborators: { en: 'Invite Collaborators', fr: 'Inviter des Collaborateurs' },
  find_products: { en: 'Find Products', fr: 'Trouver des Produits' },
  find_suppliers: { en: 'Find Suppliers', fr: 'Trouver des Fournisseurs' },
  create_video: { en: 'Create Video', fr: 'Créer une Vidéo' },
  manage_store: { en: 'Manage Store', fr: 'Gérer la Boutique' },
  store_active: { en: 'Store Active', fr: 'Boutique Active' },
  revenue_overview: { en: 'Revenue Overview', fr: 'Aperçu des Revenus' },
  export_data: { en: 'Export Data', fr: 'Exporter les Données' },
  create_order: { en: 'Create Order', fr: 'Créer une Commande' },
  gateways: { en: 'Gateways', fr: 'Passerelles' },
  connected: { en: 'Connected', fr: 'Connecté' },
  last_7_days: { en: 'Last 7 days', fr: '7 derniers jours' },
  last_30_days: { en: 'Last 30 days', fr: '30 derniers jours' },
  this_year: { en: 'This Year', fr: 'Cette Année' },
  units_sold: { en: 'units sold', fr: 'unités vendues' },
  view_all: { en: 'View All', fr: 'Voir Tout' },
  no_sales_data: { en: 'No sales data yet.', fr: 'Pas encore de données de vente.' },
  generate_to_start: { en: 'Generate your store to start.', fr: 'Générez votre boutique pour commencer.' },
  current_store: { en: 'Current Store', fr: 'Boutique Actuelle' },
  payment_status: { en: 'Payment Status', fr: 'Statut du Paiement' },
  gateways_active: { en: 'Stripe & PayPal Active', fr: 'Stripe & PayPal Actifs' },
  manage_gateway: { en: 'Manage Gateway', fr: 'Gérer la Passerelle' },
  unlock_insights: { en: 'Unlock AI Insights', fr: 'Débloquer les Aperçus IA' },
  plan_active: { en: 'Plan Active', fr: 'Plan Actif' },
  upgrade: { en: 'Upgrade', fr: 'Améliorer' },
  manage_plan: { en: 'Manage Plan', fr: 'Gérer le Plan' },
  store_owner: { en: 'Store Owner', fr: 'Propriétaire' },
  ending_soon: { en: 'Ending Soon', fr: 'Se termine bientôt' },
  account_settings: { en: 'Account Settings', fr: 'Paramètres du Compte' },
  billing_desc: { en: 'Manage your plan and payment methods.', fr: 'Gérez votre plan et vos méthodes de paiement.' },
  profile_desc: { en: 'Manage your personal details and how others see you.', fr: 'Gérez vos informations personnelles et la façon dont les autres vous voient.' },
  preferences_desc: { en: 'Customize your experience and language settings.', fr: 'Personnalisez votre expérience et vos paramètres de langue.' },
  security_desc: { en: 'Keep your account secure with these settings.', fr: 'Gardez votre compte en sécurité avec ces paramètres.' },
  danger_desc: { en: 'Permanently delete your account and all store data.', fr: 'Supprimez définitivement votre compte et toutes les données de la boutique.' },
  full_name: { en: 'Full Name', fr: 'Nom Complet' },
  email_address: { en: 'Email Address', fr: 'Adresse Email' },
  disabled: { en: 'Disabled', fr: 'Désactivé' },
  month_short: { en: 'mo', fr: 'mois' },
  welcome_dashboard: { en: "Welcome back! Here's a snapshot of your store's performance.", fr: "Bienvenue ! Voici un aperçu des performances de votre boutique." },
  paid: { en: 'Paid', fr: 'Payé' },
  mins_ago: { en: 'mins ago', fr: 'il y a quelques minutes' },
  hour_ago: { en: 'hour ago', fr: 'il y a 1 heure' },
  suggestion_price: { en: "Increase phone accessory prices by 5% to maximize profits.", fr: "Augmentez le prix des accessoires de 5% pour maximiser les profits." },
  suggestion_tiktok: { en: "Target 18-24 year olds on TikTok for better results.", fr: "Ciblez les utilisateurs de 18-24 ans sur TikTok pour de meilleurs résultats." },
  suggestion_eco: { en: "Add eco-friendly phone cases, demand is rising.", fr: "Ajoutez des coques de téléphone écologiques, la demande est en hausse." },
  winning_products: { en: 'Winning Products', fr: 'Produits Gagnants' },
  find_winning_products: { en: 'Find Winning Products', fr: 'Trouver des Produits Gagnants' },
  detector_desc: { en: 'AI-powered trending product discovery.', fr: 'Découverte de produits tendances propulsée par l\'IA.' },
  add_to_store: { en: 'Add to Store', fr: 'Ajouter à la Boutique' },
  profit_margin: { en: 'Profit Margin', fr: 'Marge de Profit' },
  demand_level: { en: 'Demand Level', fr: 'Niveau de Demande' },
  competition: { en: 'Competition', fr: 'Compétition' },
  trending_on: { en: 'Trending on', fr: 'Tendance sur' },
  suppliers: { en: 'Suppliers', fr: 'Fournisseurs' },
  reliability: { en: 'Reliability', fr: 'Fiabilité' },
  shipping_time: { en: 'Shipping Time', fr: 'Délai de Livraison' },
  high: { en: 'High', fr: 'Élevé' },
  medium: { en: 'Medium', fr: 'Moyen' },
  low: { en: 'Low', fr: 'Faible' },
  analyzing_market: { en: 'Analyzing Market Trends...', fr: 'Analyse des Tendances du Marché...' },
  added_to_store: { en: 'Added to Store!', fr: 'Ajouté à la Boutique !' },
  profit: { en: 'Profit', fr: 'Profit' },
  price: { en: 'Price', fr: 'Prix' },
  upgrade_suppliers: { en: 'Upgrade to see more suppliers', fr: 'Améliorez pour voir plus de fournisseurs' },
  popularity: { en: 'Popularity', fr: 'Popularité' },
  supplier_rating: { en: 'Supplier Rating', fr: 'Note du Fournisseur' },
  all_categories: { en: 'All Categories', fr: 'Toutes les Catégories' },
  estimated_profit: { en: 'Estimated Profit', fr: 'Profit Estimé' },
  shopify_importer: { en: 'Shopify Importer', fr: 'Importateur Shopify' },
  import_from_shopify: { en: 'Import from Shopify', fr: 'Importer de Shopify' },
  shopify_url: { en: 'Shopify Store URL', fr: 'URL de la Boutique Shopify' },
  shopify_api_key: { en: 'Admin API Access Token', fr: 'Jeton d\'Accès API Admin' },
  connect_shopify: { en: 'Connect Shopify', fr: 'Connecter Shopify' },
  import_products: { en: 'Import Products', fr: 'Importer les Produits' },
  import_pages: { en: 'Import Pages', fr: 'Importer les Pages' },
  migration_summary: { en: 'Migration Summary', fr: 'Résumé de la Migration' },
  products_imported: { en: 'Products Imported', fr: 'Produits Importés' },
  pages_imported: { en: 'Pages Imported', fr: 'Pages Importées' },
  shopify_desc: { en: 'Migrate your existing Shopify store data securely.', fr: 'Migrez les données de votre boutique Shopify existante en toute sécurité.' },
  fetching_shopify: { en: 'Fetching Shopify Data...', fr: 'Récupération des données Shopify...' },
  select_data: { en: 'Select Data to Import', fr: 'Sélectionnez les données à importer' },
  confirm_import: { en: 'Confirm Import', fr: 'Confirmer l\'Importation' },
  migration_success: { en: 'Migration Successful!', fr: 'Migration Réussie !' },
  login: { en: 'Login', fr: 'Se Connecter' },
  register: { en: 'Register', fr: 'S\'Inscrire' },
  logout: { en: 'Logout', fr: 'Déconnexion' },
  remember_me: { en: 'Remember Me', fr: 'Se Souvenir de Moi' },
  forgot_password: { en: 'Forgot Password?', fr: 'Mot de Passe Oublié ?' },
  no_account: { en: 'New to VibeShop?', fr: 'Nouveau sur VibeShop ?' },
  have_account: { en: 'Already have an account?', fr: 'Déjà un compte ?' },
  create_account: { en: 'Create Account', fr: 'Créer un Compte' },
  confirm_password: { en: 'Confirm Password', fr: 'Confirmer le Mot de Passe' },
  select_plan: { en: 'Select a Plan', fr: 'Choisir un Forfait' },
  onboarding_welcome: { en: 'Welcome to VibeShop!', fr: 'Bienvenue sur VibeShop !' },
  onboarding_step1: { en: 'Start by building your store with our AI assistant.', fr: 'Commencez par construire votre boutique avec notre assistant IA.' },
  onboarding_step2: { en: 'Find winning products and add them to your store.', fr: 'Trouvez des produits gagnants et ajoutez-les à votre boutique.' },
  onboarding_step3: { en: 'Import your existing Shopify store in seconds.', fr: 'Importez votre boutique Shopify existante en quelques secondes.' },
  got_it: { en: 'Got it!', fr: 'Compris !' },
  videos_remaining: { en: 'Videos Remaining', fr: 'Vidéos Restantes' },
  ai_config: { en: 'AI Configuration', fr: 'Configuration IA' },
  product_to_promote: { en: 'Product to Promote', fr: 'Produit à Promouvoir' },
  video_style: { en: 'Video Style', fr: 'Style de Vidéo' },
  ai_tip: { en: 'AI Tip', fr: 'Astuce IA' },
  your_creations: { en: 'Your Creations', fr: 'Vos Créations' },
  ai_video_script: { en: 'AI Video Script', fr: 'Script Vidéo IA' },
  visual: { en: 'Visual', fr: 'Visuel' },
  audio_voiceover: { en: 'Audio / Voiceover', fr: 'Audio / Voix-off' },
  use_this_script: { en: 'Use this Script', fr: 'Utiliser ce Script' },
  no_videos_generated: { en: 'No videos generated yet', fr: 'Aucune vidéo générée' },
  video_marketing_desc: { en: 'Create high-converting promotional videos for your products using AI.', fr: 'Créez des vidéos promotionnelles percutantes pour vos produits grâce à l\'IA.' },
  builder_welcome_msg: { en: "Hi! I'm your VibeShop assistant. What kind of store would you like to build today? Tell me your niche or a general idea!", fr: "Bonjour ! Je suis votre assistant VibeShop. Quel genre de boutique aimeriez-vous construire aujourd'hui ? Parlez-moi de votre niche ou d'une idée générale !" },
  builder_error: { en: "Sorry, I encountered an error while generating your store. Please try again.", fr: "Désolé, j'ai rencontré une erreur lors de la génération de votre boutique. Veuillez réessayer." },
  builder_success: { en: "I've updated your store! **{name}** is now ready in the preview. I've added {count} products in the {niche} niche. What would you like to change next?", fr: "J'ai mis à jour votre boutique ! **{name}** est maintenant prête dans l'aperçu. J'ai ajouté {count} produits dans la niche {niche}. Que souhaitez-vous changer ensuite ?" },
  back: { en: 'Back', fr: 'Retour' },
  done: { en: 'Done', fr: 'Terminé' },
  review_selection: { en: 'Review your selection before finalizing', fr: 'Vérifiez votre sélection avant de finaliser' },
  source_url: { en: 'Source URL', fr: 'URL Source' },
  items: { en: 'Items', fr: 'Articles' },
  about_contact: { en: 'About & Contact', fr: 'À propos & Contact' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
